### ISSUE TITLE
fatal error when run into 'android' phone

### ISSUE THREAD

**Issue by Manolo1988** [solrex/caffe-mobile#20]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.yangwenbo.caffesimple, PID: 12112
                                                   java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.yangwenbo.caffesimple-2/base.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.yangwenbo.caffesimple-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.yangwenbo.caffesimple-2/lib/arm64, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libcaffe-jni.so"
                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                                       at java.lang.System.loadLibrary(System.java:1533)
                                                       at com.yangwenbo.caffesimple.MainActivity.<clinit>(MainActivity.java:116)
                                                       at java.lang.Class.newInstance(Native Method)
                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1083)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:199)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by solrex** [comment]
@Manolo1988 Have you successfully built libcaffe-jni.so? Try to find libcaffe-jni.so in your building directory.
